version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]
    ignore:
      - dependency-name: react
      - dependency-name: react-native
      - dependency-name: "@types/react"
      - dependency-name: typescript
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-and-patch:
        update-types: [minor, patch]
